name: Call Docker Build Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker-image.yml
    with:
      ECR_REGION: us-east-1
      ECR_REPOSITORY_NAME: my-repo
      IMAGE_NAME: my-image
      STACK_NAME: my-stack 
  output:
    needs: call-docker-build
    uses: ./.github/workflows/value.yml
    with:
      IMAGE_NAME: "${{ needs.call-docker-build.outputs.docker-tag }}"

  
