on:
  push:
    branches:
      - 'develop/*'

  workflow_dispatch:

jobs:
  main:
    uses: GudditiOrg/Docker-Resume/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@develop/*
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
