on:
  push:
    branches:
      - 'develop/*'
  workflow_dispatch:

jobs:
  develop:
    uses: ./.github/workflows/REUSABLE_WORKFLOW_FILE.yml
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}./.github/workflows/
  job1:
    uses: ./.github/workflows/Reusable.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
