on:
  push:
    branches:
      - 'develop/*'
  workflow_dispatch:

jobs:
  develop:
      - name: Run reusable workflow
        uses: ./.github/workflows/REUSABLE_WORKFLOW_FILE.yml
        with:
          image_name: my-awesome-app
          tag: ${{ github.run_number }}
