name: build-and-push

on:
  workflow_call:
    inputs:
        ECR_REGION:
            description: "ECR region name" 
            required: false
            type: string
        ECR_REPOSITORY_NAME:
            description: "ECR repo name "
            required: false
            type: string
        IMAGE_NAME:
            description: "Stack image name"
            required: false
            type: string
        STACK_NAME:
            description: "Stack name"
            required: false
            type: string
    outputs:
        docker-tag:
            description: "Exporting docker image name as output"
            value: ${{ jobs.docker-build.outputs.docker-tag }}
  

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
        docker-tag: ${{ steps.docker-tag.outputs.docker-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker image build and test coverage
        id: docker-tag
        run: |
            docker build -t $DOCKER_IMAGE:$TAG .
            image=$DOCKER_IMAGE:$TAG
            echo "docker-tag=${image}" >> "$GITHUB_OUTPUT"
        env:
            DOCKER_IMAGE: ${{ inputs.ECR_REPOSITORY_NAME }}
            TAG: ${{ github.sha }}
