name: docker-build

on:
  workflow_call:
    inputs:
        ECR_REGION:
            description: "ECR region name" 
            required: false
            default: "us-east-1"
            type: string
        ECR_REPOSITORY_NAME:
            description: "ECR repo name "
            required: false
            default: "chat"
            type: string
        IMAGE_NAME:
            description: "Stack image name"
            required: false
            default: "chat"
            type: string
        STACK_NAME:
            description: "Stack name"
            required: false
            default: "chat"
            type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build and test coverage
        run: |
            docker build -t $docker_image:$tag .
        env:
            docker_image: ${{ inputs.ECR_REPOSITORY_NAME }}
            tag: ${{ github.sha }}
            
      - name: Build, tag, and push docker image to Amazon ECR
        id: step1
        env:
          REGISTRY: "amazon"
          docker_name: ${{ inputs.ECR_REPOSITORY_NAME }}:${{ github.sha }}
        run: |
          docker tag $docker_name $REGISTRY/$docker_name
          docker images
