
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gudditi/nginx-resume:latest
    - name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v3
      with:
        image: gudditi/nginx-resume:latest
        annotations: true
