
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    uses: GudditiOrg/Docker-Resume/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@main
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
