on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  main:
    if: github.ref == 'refs/heads/main'
    uses: GudditiOrg/Docker-Resume/.github/workflows/REUSABLE_WORKFLOW_FILE.yml
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}

  develop:
    if: github.ref == 'refs/heads/develop'
    uses: GudditiOrg/Docker-Resume/.github/workflows/REUSABLE_WORKFLOW_FILE.yml
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}
