name: docker-build

on:
  push:
  

env:
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"
  IMAGE_TAG: ${{ github.sha }}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build and test coverage
        run: |
            docker build -t ${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }} .
            docker images
            
      - name: Build, tag, and push docker image to Amazon ECR
        id: step1
        env:
          REGISTRY: "amzon"
          REPOSITORY: ${{ env.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }} $REGISTRY/$REPOSITORY:${{ github.sha }}
          docker images
