name: Manual Trigger with Inputs

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1 description'
        required: true
        default: 'Default value 1'
      input2:
        description: 'Input 2 description'
        required: true
        default: 'false'

jobs:
  my_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.input2 == 'true' }}

    steps:
      - name: Display Inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"
    

  qa_cdk-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
