on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/REUSABLE_WORKFLOW_FILE.yml
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
