on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  develop:
    uses: ./.github/workflows/REUSABLE_WORKFLOW_FILE.yml
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}

  output:
    runs-on: ubuntu
    needs: develop
    steps:
      - name: Call output
        id: get-output
        env:
          DOCKER_IMAGE: ${{ needs.develop.outputs.docker-build-image-name }}
        run: echo $DOCKER_IMAGE

      - name: Next Step
        run: |
          echo "The Docker image is ${{ steps.get-output.outputs.DOCKER_IMAGE }}"
