name: Manual Approval

on:
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Approve the step manually'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"

      - name: Manual Approval Step
        run: echo "This step requires manual approval"

      - name: Step 2
        run: echo "Running Step 2"
        if: env.APPROVED == 'true'

      - name: Step 3
        run: echo "Running Step 3"
