name: Infra automation -> Dev -> QA
on:
  pull_request:
    branches:
      - main
      - test-1
  workflow_dispatch:

env:
  REGION: us-east-1

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:        
      - name: checkout code from repo
        uses: actions/checkout@v3
  
  dev_cdk-diff:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
     

  dev_cdk-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.manual_approval == 'true' }}
    needs: dev_cdk-diff
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
      


  qa_cdk-diff:
    runs-on: ubuntu-latest
    needs: test
   
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
    

  qa_cdk-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.manual_approval == 'true' }}
    needs: qa_cdk-diff
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
    
