name: Two Jobs Workflow

on:
  workflow_run:
    workflows: ["Your Workflow Name"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 executed normally"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Step 1
        run: echo "Job 2 executed"

      - name: Manual Approval
        if: always()
        uses: repo-sync/prompt@v1
        with:
          prompt: "Manual approval required. Do you want to proceed?"
          confirm-text: "Proceed"
