name: Execute Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Custom event for manual trigger

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Executing Job 1"

  job2:
    needs: job1
    if: github.event_name == 'workflow_run' && github.event.workflow == 'Execute Jobs' && github.event.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Holding Job 2"
        if: false  # Skip this step initially
      - name: Step 2
        run: echo "Executing Job 2"
