name: Execute Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Custom event for manual trigger

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Executing Job 1"

  job2:
    needs: job1
    if: github.event == 'workflow_dispatch' || github.event == 'manual'  # Execute on manual trigger or workflow_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Executing Job 2"
      - name: Step 2
        run: echo "This step will only execute when Job 2 is manually triggered"
