name: Infra automation -> Dev -> QA
on:
  push:
    branches:
      - "anji/GitHub-actions"
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Approve the job manually (true -> approve) (false -> cancel) '
        required: true
        default: 'false'
env:
  REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Manual Approval Step
        if: ${{ github.event.inputs.manual_approval == 'true' }}
        run: echo "Job is approved and can proceed"

      - name: Step 2
        run: echo "Running Step 2"
        


  dev_cdk-diff:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3

  dev_cdk-deploy:
    runs-on: ubuntu-latest
    needs: dev_cdk-diff
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3

  qa_cdk-diff:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3

  qa_cdk-deploy:
    runs-on: ubuntu-latest
    needs: qa_cdk-diff
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t gudditi/image:latest .
