name: Manual Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"

  manual_approval:
    needs: job2
    runs-on: ubuntu-latest
    if: ${{ needs.job2.result == 'success' }}
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Workflow manual approval'
          title: 'Manual Approval Required'
          branch: 'manual-approval'
          base: 'main'
          body: 'Please review and approve this workflow run.'
