name: Execute Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Custom event for manual trigger

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Executing Job 1"

  job2:
    needs: job1
    if: github.event == 'workflow_dispatch'  # Only execute on manual trigger
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Holding Job 2"
      - name: Step 2
        run: echo "This step will not be executed unless Job 2 is manually triggered"
