name: Manual Approval

on:
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Approve the job manually (true -> approve) (false -> cancel) '
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"

      - name: Manual Approval Step
        if: ${{ github.event.inputs.manual_approval == 'true' }}
        run: echo "Job is approved and can proceed"

      - name: Step 2
        run: echo "Running Step 2"
