name: Manual Approval

on:
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Approve the job manually'
        required: true
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        run: docker build -t gudditi/docker:latest .

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval Step
        if: ${{ github.event.inputs.manual_approval == 'true' }}
        run: echo "Job is approved and can proceed"
