name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."
          # Add your build commands here

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here

  hold:
    needs: deploy
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Manual Approval
        id: approval
        uses: actions/github-script@v5
        with:
          script: |
            const { data: pullRequest } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.sha,
              state: 'open'
            });
            const { data: checks } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            const { data: statuses } = await github.repos.listStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            
            const isPullRequest = pullRequest.length > 0;
            const hasChecks = checks.total_count > 0;
            const hasPendingStatuses = statuses.some(status => status.state === 'pending');
            
            if (isPullRequest || hasChecks || hasPendingStatuses) {
              core.setFailed('Cannot approve manually if there are pending checks or pull requests.');
              return;
            }
            
            core.setOutput('approved', 'true');
            console.log('Manual approval granted.');

      - name: Proceed with Deployment
        if: steps.approval.outputs.approved == 'true'
        # Job steps to proceed with the deployment
