name: Two Jobs Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 executed normally"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Step 1
        run: echo "Job 2 executed"

      - name: Manual Approval
        if: always()
        run: |
          echo "Manual approval required. Proceed with the next step?"
          echo "::set-output name=approval::${{ steps.approval.outputs.approved }}"

  job3:
    needs: [job2]
    runs-on: ubuntu-latest
    if: needs.job2.result == 'success' && needs.job2.outputs.approval == 'true'
    steps:
      - name: Step 1
        run: echo "Job 3 executed"

  job4:
    needs: [job3]
    runs-on: ubuntu-latest
    if: needs.job3.result == 'success'
    steps:
      - uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: user1,user2
            minimum-approvals: 1
            issue-title: "Deploying v1.3.5 to prod from staging"
