name: build-and-push

on:
  workflow_call:
    inputs:
        IMAGE_NAME:
            description: "Stack image name"
            required: false
            type: string
  

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
        docker-tag: ${{ steps.docker-tag.outputs.docker-tag }}
    steps:
      - name: Checkout code
        run: echo ${{ inputs.IMAGE_NAME }}
